import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {intentFixture} from './fixtures/intentRolePolicySyntheticV3';
import {runIntentRolePolicyBridgeV3} from '../../src/engine-v3/evaluation/intentRolePolicyBridgeV3';
const load=new Function('p','return import(p)') as (p:string)=>Promise<any>;
const moduleAt=(f:string)=>load(pathToFileURL(join(process.cwd(),'scripts',f)).href);
const H='a'.repeat(64),AT='2099-09-01T12:00:00Z';
function claim(value:any,scope:any,field='invented',applicability='OFFER_SCOPED'):any{
 return {state:value===null?'UNKNOWN':'KNOWN',value:structuredClone(value),reason:'Invented explicit evidence, not real material',observedAt:AT,timeSource:'SYNTHETIC_DECLARATION',scope:structuredClone(scope),applicability,
   links:[{field,evidence:[{ref:'SYNTHETIC_PROOF',sha256:H}]}]};
}
async function fixture(){
 const m=await moduleAt('diagnostic-offer-requirements-v1.mjs'),b=intentFixture();
 b.search.maximumDistanceKm=3;b.distance.semantics='strong-preference';
 const party={adults:2,childAgesAtStay:[],unitsRequested:1,requirements:{sleepingPlaces:true,capacity:true,childAdmission:false,exclusiveUse:false,privateBathroom:false}};
 const stay={checkIn:b.search.checkIn,checkOut:b.search.checkOut,currency:'EUR'};
 const reference={kind:'SELECTED_LOCATION',id:'INVENTED_ORIGIN',provenance:'Explicit synthetic selected point',point:{latitude:0,longitude:0}};
 const n:any={version:m.DIAGNOSTIC_REQUIREMENTS_VERSION,caseId:b.caseId,mode:'SYNTHETIC',evaluatedAt:AT,party,stay,
  geography:{commonReference:claim(reference,null,'reference','SET_DOCUMENTED'),contexts:[{id:'PREFERENCE',semantics:'strong-preference',kilometers:3}]},
  offers:b.search.hotels.map(h=>{const rate=h.offers[0],scope={roomKey:rate.roomName,rateKey:rate.id};const c=(v:any)=>claim(v,scope);return {alternativeId:h.id,
   scope:{...scope,stay,party:{adults:2,childAgesAtStay:[],unitsRequested:1}},reference:c(reference),distanceKm:c(h.distance),
   availability:{observed:c('AVAILABLE'),bookability:c(true),unavailable:c(null)},unitsOffered:c(1),internalRooms:c(1),capacityGuests:c(2),
   sleeping:c({complete:true,beds:[{kind:'DOUBLE',count:1,placesPerBed:2,placeBasis:'Explicit two-person bed in synthetic evidence'}]}),
   children:{admitted:c(null),minimumAge:c(null),adultPricingFromAge:c(null),extraBedsAvailable:c(null)},exclusiveUse:c(null),privateBathroom:c(null),
   completeTotal:c(rate.totalKnownCost),ratingScale:c(10),ratingObserved:c(h.reviewScore)};})};
 return {m,n,b,run:()=>m.evaluateDiagnosticOfferRequirements(n),prepare:()=>m.prepareSupportedIntentBridgeInput(n,b)};
}
const state=(c:any,state:string,value:any=null)=>Object.assign(c,{state,value});
function family(x:any,ages=[8,13]){x.n.party.childAgesAtStay=ages;x.n.party.requirements.childAdmission=true;x.b.search.children=ages.length;
 for(const o of x.n.offers){o.scope.party.childAgesAtStay=ages;o.capacityGuests.value=4;o.children.admitted.value=true;o.children.admitted.state='KNOWN';
 o.sleeping.value.beds=[{kind:'DOUBLE',count:1,placesPerBed:2,placeBasis:'Explicit synthetic pair'},{kind:'SINGLE',count:2,placesPerBed:1,placeBasis:'Explicit synthetic single places'}];}}
test('OR01 complete supported input traverses existing bridge with identical output and input',async()=>{const x=await fixture(),before=JSON.stringify(x.b),p=x.prepare();assert.equal(p.status,'SUPPORTED_DIAGNOSTIC_INPUT');assert.deepEqual(p.input,x.b);const a=runIntentRolePolicyBridgeV3(x.b);assert.deepEqual(runIntentRolePolicyBridgeV3(p.input),a);assert.equal(JSON.stringify(x.b),before);});
test('OR02 source centre common identity supports diagnostics, never selected-point conversion',async()=>{const x=await fixture();const ref={kind:'SOURCE_CENTRE',id:'SYNTHETIC_SOURCE_CENTRE',provenance:'Same declared source reference',point:null};x.n.geography.commonReference.value=ref;x.n.offers.forEach((o:any)=>o.reference.value=ref);const p=x.prepare();assert(p.assessment.offers.every((o:any)=>o.geography.state==='COMPARABLE_SOURCE_DECLARED'&&!o.geography.selectedLocationEquivalenceVerified));assert.equal(p.input,null);});
test('OR03 incompatible and ambiguous references stay non-comparable',async()=>{const x=await fixture();x.n.offers[0].reference.value.id='OTHER_ORIGIN';assert.equal(x.run().offers[0].geography.state,'NON_COMPARABLE');state(x.n.geography.commonReference,'UNKNOWN');assert.equal(x.run().offers[0].geography.state,'REFERENCE_UNVERIFIED');});
test('OR04 strong preference boundary reuses exact <=; outside is not hard violation or tolerance',async()=>{const x=await fixture();x.n.offers[0].distanceKm.value=3.2;const g=x.run().offers[0].geography.contexts[0];assert.equal(g.status,'OUTSIDE_REQUIRES_JUSTIFIED_EXCEPTION');assert.equal(g.hardViolation,false);assert.equal(g.exceptionAuthorized,false);assert.equal(g.generalToleranceKm,null);x.n.offers[0].distanceKm.value=3;assert.equal(x.run().offers[0].geography.contexts[0].status,'WITHIN_PREFERENCE');});
test('OR05 complete synthetic context agrees with actual strong-distance statuses',async()=>{const x=await fixture();const r=runIntentRolePolicyBridgeV3(x.b),a=x.run();for(const o of a.offers){const c=r.candidates.find(c=>c.hotelId===o.alternativeId)!;assert.equal(o.geography.contexts[0].status==='WITHIN_PREFERENCE',c.distance?.status==='satisfied');}});
test('OR06 observed availability preserves unknown bookability and prevents boolean coercion',async()=>{const x=await fixture();state(x.n.offers[0].availability.bookability,'UNKNOWN');const p=x.prepare(),a=p.assessment.offers[0].availability;assert.equal(a.state,'OBSERVED_AVAILABLE');assert.equal(a.bridgeBoolean,null);assert.equal(a.qualityEffect,'NONE');assert.equal(p.input,null);});
test('OR07 known unavailable, verified not bookable and unknown remain separate',async()=>{const x=await fixture(),a=x.n.offers[0].availability;state(a.observed,'UNKNOWN');state(a.bookability,'UNKNOWN');assert.equal(x.run().offers[0].availability.state,'UNKNOWN');state(a.unavailable,'KNOWN',true);assert.equal(x.run().offers[0].availability.state,'KNOWN_UNAVAILABLE');assert.equal(x.run().offers[0].availability.bridgeBoolean,null);state(a.unavailable,'UNKNOWN');state(a.bookability,'KNOWN',false);assert.equal(x.run().offers[0].availability.state,'VERIFIED_NOT_BOOKABLE');});
test('OR08 conflicting availability never yields a bridge boolean',async()=>{const x=await fixture();state(x.n.offers[0].availability.unavailable,'KNOWN',true);assert.equal(x.run().offers[0].availability.state,'CONFLICTING');assert.equal(x.prepare().input,null);});
test('OR09 exact rate scope and evidence timestamp checked',async()=>{for(const mutation of [(n:any)=>n.offers[0].scope.party.adults=8,(n:any)=>n.offers[0].capacityGuests.scope.rateKey='OTHER_RATE',(n:any)=>n.offers[0].availability.observed.observedAt='2100-01-01T00:00:00Z']){const x=await fixture();mutation(x.n);assert.throws(x.run,/REQUIREMENTS_/);}});
test('OR10 four documented places and correct ages are evaluated, composition unchanged',async()=>{const x=await fixture();family(x);const a=x.run().offers[0].accommodation;assert.equal(a.status,'SATISFIED');assert.equal(a.sleeping.exactPlaces,4);assert.deepEqual(a.partyUnchanged.childAgesAtStay,[8,13]);assert.equal(a.partyUnchanged.adults,2);assert.equal(x.prepare().status,'SUPPORTED_DIAGNOSTIC_INPUT');});
test('OR11 insufficient documented bed inventory is a violation, incomplete inventory is missing not bad quality',async()=>{const x=await fixture();family(x);x.n.offers[0].sleeping.value.beds.pop();let a=x.run().offers[0].accommodation;assert.equal(a.sleeping.status,'DOCUMENTED_VIOLATION');assert.equal(a.capacity.status,'SATISFIED');x.n.offers[0].sleeping.value.complete=false;a=x.run().offers[0].accommodation;assert.equal(a.sleeping.status,'INSUFFICIENT_INFORMATION');assert.equal(a.qualityEffect,'NONE');});
test('OR12 sofa without places remains unknown despite advertised capacity',async()=>{const x=await fixture();family(x);x.n.offers[0].sleeping.value.beds[1]={kind:'SOFA',count:1,placesPerBed:null,placeBasis:'Places undocumented'};const a=x.run().offers[0].accommodation;assert.equal(a.sleeping.exactPlaces,null);assert.equal(a.sleeping.documentedLowerBound,2);assert.equal(a.sleeping.status,'INSUFFICIENT_INFORMATION');assert.equal(a.capacity.status,'SATISFIED');});
test('OR13 bunk count does not multiply sleeping places or certify exclusivity',async()=>{const x=await fixture();family(x);x.n.offers[0].sleeping.value.beds=[{kind:'BUNK',count:3,placesPerBed:null,placeBasis:'Inventory word only'}];const a=x.run().offers[0].accommodation;assert.equal(a.sleeping.documentedLowerBound,0);assert.equal(a.sleeping.exactPlaces,null);assert.equal(a.privacy.exclusiveUse.status,'NOT_REQUIRED');assert.equal(x.n.offers[0].exclusiveUse.value,null);});
test('OR14 suite with two internal rooms remains one offered unit',async()=>{const x=await fixture();family(x);x.n.offers[0].internalRooms.value=2;const a=x.run().offers[0].accommodation;assert.equal(a.units.status,'SATISFIED');assert.equal(a.sleeping.exactPlaces,4);assert.equal(a.internalRooms.value,2);});
test('OR15 age-dependent adult pricing never changes party or implies a violation',async()=>{const x=await fixture();family(x);state(x.n.offers[0].children.adultPricingFromAge,'KNOWN',5);const a=x.run().offers[0].accommodation;assert.deepEqual(a.childPricing.childIndexesChargedAtAdultRate,[0,1]);assert.equal(a.childPricing.status,'EVALUATED_TARIFF_TREATMENT');assert.equal(a.ageAdmission.status,'SATISFIED');assert.equal(a.partyUnchanged.adults,2);});
test('OR16 child admission violations, unknowns and conflicting age claims are distinct',async()=>{const x=await fixture();family(x);const c=x.n.offers[0].children;state(c.admitted,'KNOWN',false);assert.equal(x.run().offers[0].accommodation.ageAdmission.status,'DOCUMENTED_VIOLATION');state(c.admitted,'UNKNOWN');assert.equal(x.run().offers[0].accommodation.ageAdmission.status,'INSUFFICIENT_INFORMATION');state(c.minimumAge,'KNOWN',12);assert.equal(x.run().offers[0].accommodation.ageAdmission.status,'DOCUMENTED_VIOLATION');state(c.admitted,'KNOWN',true);assert.equal(x.run().offers[0].accommodation.ageAdmission.status,'CONFLICTING');c.admitted.applicability='PROPERTY_WIDE';assert.equal(x.run().offers[0].accommodation.ageAdmission.status,'DOCUMENTED_VIOLATION');});
test('OR17 property-wide child pricing is evaluated but not certified for a specific rate',async()=>{const x=await fixture();family(x);const c=x.n.offers[0].children.adultPricingFromAge;state(c,'KNOWN',5);c.applicability='PROPERTY_WIDE';const a=x.run().offers[0].accommodation;assert.equal(a.childPricing.rateApplicabilityVerified,false);assert.equal(a.childPricing.status,'EVALUATED_POLICY_RATE_APPLICABILITY_UNVERIFIED');});
test('OR18 privacy is tested only when requested; private unit is not adequate beds',async()=>{const x=await fixture();family(x);state(x.n.offers[0].exclusiveUse,'KNOWN',true);state(x.n.offers[0].sleeping,'UNKNOWN');assert.equal(x.run().offers[0].accommodation.sleeping.status,'INSUFFICIENT_INFORMATION');x.n.party.requirements.privateBathroom=true;assert.equal(x.run().offers[0].accommodation.privacy.privateBathroom.status,'INSUFFICIENT_INFORMATION');state(x.n.offers[0].privateBathroom,'KNOWN',false);assert.equal(x.run().offers[0].accommodation.privacy.privateBathroom.status,'DOCUMENTED_VIOLATION');});
test('OR19 UNKNOWN complete total can compute diagnostically but cannot recommend incomplete candidates',async()=>{const x=await fixture();for(const [i,h]of x.b.search.hotels.entries()){state(x.n.offers[i].completeTotal,'UNKNOWN');h.totalKnownCost=null;h.taxesIncluded=null;h.offers[0].totalKnownCost=null;h.offers[0].taxesIncluded=null;}const p=x.prepare();assert.equal(p.status,'SUPPORTED_DIAGNOSTIC_INPUT');const r=runIntentRolePolicyBridgeV3(p.input);assert.equal(r.decision.status,'abstained');assert(r.policyInput.solutions.every(s=>s.totalCost===null));assert(p.assessment.offers.every((o:any)=>o.recommendationBlockers.includes('COMPLETE_TOTAL_UNVERIFIED')));});
test('OR20 unknown scale omits rating, retaining original observation; other evidence can compute',async()=>{const x=await fixture();for(const [i,h]of x.b.search.hotels.entries()){state(x.n.offers[i].ratingScale,'UNKNOWN');h.reviewScore=null;h.availableData.hasReviewScore=false;}const p=x.prepare();assert.equal(p.status,'SUPPORTED_DIAGNOSTIC_INPUT');assert(p.assessment.offers.every((o:any)=>o.rating.observation.value!==null&&!o.rating.normalizable));assert.equal(runIntentRolePolicyBridgeV3(p.input).scope,'OFFLINE_EVALUATION_ONLY');});
test('OR21 no hidden selected-rate fallback or unknown normalization coercion',async()=>{for(const kind of ['offer','rating','total','point','distance']){const x=await fixture();if(kind==='offer')x.b.search.hotels[0].offers.push(structuredClone(x.b.search.hotels[0].offers[0]));if(kind==='rating')state(x.n.offers[0].ratingScale,'UNKNOWN');if(kind==='total')state(x.n.offers[0].completeTotal,'UNKNOWN');if(kind==='point')x.b.search.selectedLocation!.latitude=9;if(kind==='distance')x.b.search.hotels[0].distance=99;assert.throws(x.prepare,/REQUIREMENTS_/);}});
test('OR22 order and provider names cannot change requirement results or input merit',async()=>{const x=await fixture(),a=x.run();x.n.offers.reverse();x.b.search.hotels.reverse();for(const h of x.b.search.hotels){h.provider='other-synthetic-source';h.offers[0].provider=h.provider;}assert.deepEqual(x.run().offers.sort((a:any,b:any)=>a.alternativeId.localeCompare(b.alternativeId)),a.offers.sort((a:any,b:any)=>a.alternativeId.localeCompare(b.alternativeId)));assert.equal(x.prepare().status,'SUPPORTED_DIAGNOSTIC_INPUT');});
test('OR23 known zero/false is not UNKNOWN, unknown is not a numeric default',async()=>{const x=await fixture();state(x.n.offers[0].distanceKm,'KNOWN',0);assert.equal(x.run().offers[0].geography.contexts[0].status,'WITHIN_PREFERENCE');state(x.n.offers[0].capacityGuests,'UNKNOWN',0);assert.throws(x.run,/UNKNOWN_OR_CONFLICT_VALUE/);});
test('OR24 state/conflict, missing references and different points fail closed',async()=>{const x=await fixture();state(x.n.offers[0].sleeping,'CONFLICTING');assert.equal(x.run().offers[0].accommodation.status,'CONFLICTING');x.n.offers[0].reference.value=structuredClone(x.n.offers[0].reference.value);x.n.offers[0].reference.value.point.latitude=1;assert.equal(x.run().offers[0].geography.state,'CONFLICTING');x.n.offers[0].capacityGuests.links=[];assert.throws(x.run,/KNOWN_CLAIM_UNSUPPORTED/);});
test('OR25 pure assessment never executes a decision, performs custody or admits Golden',async()=>{const x=await fixture(),a=x.run();assert.equal(a.engineExecuted,false);assert.equal(a.decision,null);assert.equal(a.abstention,null);assert.equal(a.automaticGoldenAdmission,false);for(const f of ['diagnostic-offer-requirements-v1.mjs','reviewed-intent-input-assessment-v2.mjs'])assert.doesNotMatch(readFileSync(join(process.cwd(),'scripts',f),'utf8'),/from ['"]node:(fs|http)|\bfetch\s*\(|writeFile|runIntentRolePolicyBridgeV3\s*\(/);});

// Integration with the real, immutable D0050 verifier, on invented review data.
async function reviewedFixture(){
 const x=await fixture(),d=await moduleAt('diagnostic-transcription-review-v1.mjs'),v1=await moduleAt('reviewed-intent-input-assessment-v1.mjs'),v2=await moduleAt('reviewed-intent-input-assessment-v2.mjs');
 const hash=(x:any)=>d.sha256(d.json(x)),s=x.b.search;
 const manifest={caseId:x.n.caseId,profile:'Balanced',scenario:{budgetTotal:s.totalBudget,nights:s.nights,adults:s.adults,children:0,childAgesAtStay:[],rooms:1,currency:'EUR',checkIn:s.checkIn,checkOut:s.checkOut,needs:[{requirement:'Invented adequate sleeping places and guest capacity',essential:true}]}};
 const wrap=(v:any)=>({status:v===null?'UNKNOWN':'KNOWN',value:v,reliability:v===null?'UNKNOWN':'LOW',reason:v===null?'Synthetic missing evidence':null,evidenceRefs:['SYNTHETIC_PROOF']});
 const packet:any={schemaVersion:d.VERSION,caseId:x.n.caseId,mode:'SYNTHETIC_TEST',classification:'DIAGNOSTIC_ONLY',humanReview:'PENDING',custodyCreated:false,sourceArchiveSha256:H,scenario:{currency:'EUR'},proofs:[{ref:'SYNTHETIC_PROOF',path:'invented.png',sha256:H}],alternatives:x.b.search.hotels.map(h=>({id:h.id,proofs:[],fields:Object.entries({stay:{checkIn:s.checkIn,checkOut:s.checkOut},occupancy:{adults:2,children:0,childAges:[],rooms:1},currency:'EUR',roomName:h.offers[0].roomName,rateName:null,selection:'Invented selected rate',displayedPrice:h.price,cancellation:'Invented conditions',completeTotal:null,rating:h.reviewScore,ratingScale:null,distance:String(h.distance)+' km dal centro',beds:'Invented two-person bed',roomCapacity:'Two guests',availability:'Public observed rate'}).map(([key,v])=>({key,critical:true,reviewStatus:'PENDING',sourceKind:v===null?'UNKNOWN':'OBSERVED',value:wrap(v)}))}))};
 // Same invented two-place configuration, expressed in the bounded supported
 // lexical grammar; the original source observation is sealed before review.
 for(const a of packet.alternatives)a.fields.find((f:any)=>f.key==='beds').value.value='1 letto matrimoniale';
 let state=d.initialReview(packet,H);const events:any[]=[];
 const append=(a:any)=>{const action={...a,caseId:packet.caseId,expectedRevision:state.revision,contentFingerprint:d.fingerprint(state)},body={schemaVersion:d.VERSION,ordinal:state.revision+1,packetHash:state.packetHash,codeHash:H,previousHash:state.lastEventHash,recordedAt:AT,actor:'SYNTHETIC_TEST',action};const event={...body,eventHash:hash(body)};state=d.applyReview(state,action,packet);state.lastEventHash=event.eventHash;events.push(event);};
 for(const a of packet.alternatives)for(const f of a.fields)append({type:'REVIEW_FIELD',alternativeId:a.id,fieldKey:f.key,reviewStatus:'CORRECT'});append({type:'CONFIRM_REVIEW',confirmed:true});
 const preparedInput={caseId:packet.caseId,classification:'DIAGNOSTIC_ONLY',originalScenario:packet.scenario,originalScenarioManifestSha256:hash(manifest),alternatives:packet.alternatives.map((a:any)=>({alternativeId:a.id,fields:a.fields.map((f:any)=>({key:f.key,value:f.value}))})),postObservationContexts:[{contextId:'PREFERENCE',budgetMinorUnits:s.totalBudget!*100,currency:'EUR',prospectivelyFrozen:false,independentCase:false,distancePreference:{kilometers:3,semantics:'STRONG_PREFERENCE_WITH_JUSTIFIED_EXCEPTIONS',hardMaximum:false,generalToleranceKm:null}}]};
 const args={packet,events,codeHash:H,originalManifest:manifest,originalManifestSha256:hash(manifest),preparedInput,preparedInputSha256:hash(preparedInput)};
 const old=v1.assessReviewedIntentInput(args),n=x.n;n.reviewProjectionFingerprint=old.projectionFingerprint;n.requirementBasis=manifest.scenario.needs;
 n.requirementMapping=Object.entries(n.party.requirements).map(([key,value])=>({key,needIndexes:value?[0]:[],reason:'Explicit synthetic scenario mapping'}));
 const ref={kind:'SOURCE_CENTRE',id:'SYNTHETIC_COMMON',point:null,provenance:'Same documented invented source centre'};
 n.geography.commonReference.value=ref;n.geography.commonReference.links=[{field:n.offers[0].alternativeId+'/distance',evidence:[{ref:'SYNTHETIC_PROOF',sha256:H}]}];
 for(const o of n.offers){const c=old.projection.candidates.find((c:any)=>c.alternativeId===o.alternativeId);o.reviewedOfferBindingFingerprint=hash(c.offerBinding);o.scope.rateKey='REVIEWED_RATE_'+o.reviewedOfferBindingFingerprint;
  const visit=(v:any)=>{if(v&&typeof v==='object'){if(v.state){v.scope={roomKey:o.scope.roomKey,rateKey:o.scope.rateKey};v.links=[{field:'beds',evidence:[{ref:'SYNTHETIC_PROOF',sha256:H}]}];}else for(const z of Object.values(v))visit(z);}};visit(o);o.reference.value=ref;stateClaim(o.completeTotal);stateClaim(o.ratingScale);stateClaim(o.availability.bookability);o.sleeping.value=x.m.normalizeItalianBedInventory('1 letto matrimoniale');}
 function stateClaim(c:any){c.state='UNKNOWN';c.value=null;}
 return {x,args,n,old,v2,run:()=>v2.assessReviewedIntentRequirements(args,n)};
}
test('OR26 successor revalidates confirmed history and preserves every original UNKNOWN',async()=>{const f=await reviewedFixture(),before=JSON.stringify(f.args),a=f.run();assert.deepEqual(a.missingness,f.old.missingness);assert.equal(a.reviewConfirmed,true);assert.equal(a.engineInput,null);assert.equal(a.engineExecuted,false);assert.equal(JSON.stringify(f.args),before);});
test('OR27 successor rejects changed binding, other-rate proof and UNKNOWN promotion',async()=>{for(const kind of ['binding','rate','proof','unknown','availability','requirement','beds','rating','age']){const f=await reviewedFixture();if(kind==='binding')f.n.reviewProjectionFingerprint=H;if(kind==='rate')f.n.offers[0].scope.rateKey='OTHER_RATE';if(kind==='proof')f.n.offers[0].sleeping.links[0].evidence[0].sha256='b'.repeat(64);if(kind==='unknown')f.n.offers[0].ratingObserved.links[0].field='ratingScale';if(kind==='availability')state(f.n.offers[0].availability.bookability,'KNOWN',true);if(kind==='requirement')f.n.party.requirements.exclusiveUse=true;if(kind==='beds')state(f.n.offers[0].sleeping,'KNOWN',{complete:true,beds:[{kind:'DOUBLE',count:9,placesPerBed:2,placeBasis:'Unjustified change'}]});if(kind==='rating')f.n.offers[0].ratingObserved.value=7.7;if(kind==='age')state(f.n.offers[0].children.adultPricingFromAge,'KNOWN',7);assert.throws(f.run,/REVIEWED_REQUIREMENTS_/);}});
test('OR28 feedback injection cannot change the successor assessment',async()=>{const f=await reviewedFixture(),a=f.run();(f.args as any).feedback={winner:'invented'};assert.deepEqual(f.run(),a);assert.equal(a.bestOverBudget,'UNMAPPED_NOT_UPGRADE');});
test('OR29 lexical Italian single/double variants preserve complete synthetic inventories',async()=>{const {m}=await fixture();for(const text of ['1 letto matrimoniale e 3 letti singoli','3 letti singoli; 1 letto matrimoniale large']){const b=m.normalizeItalianBedInventory(text);assert(b);assert.equal(b.beds.reduce((n:number,b:any)=>n+b.count*b.placesPerBed,0),5);}});
test('OR30 lexical sofa and bunk never fabricate places; ambiguous or negated text rejected',async()=>{const {m}=await fixture();assert.equal(m.normalizeItalianBedInventory('2 divani letto').beds[0].placesPerBed,null);assert.equal(m.normalizeItalianBedInventory('3 letti a castello (dicitura testuale del sito)').beds[0].placesPerBed,null);for(const t of ['1 letto singolo oppure 1 letto matrimoniale','nessun letto singolo','1 letto matrimoniale con posti ulteriori','UNKNOWN'])assert.equal(m.normalizeItalianBedInventory(t),null);});
test('OR31 two internal room labels are not multiplicative bed or unit quantities',async()=>{const {m}=await fixture(),b=m.normalizeItalianBedInventory('Camera 1: 2 letti singoli; Camera 2: 2 letti singoli');assert.equal(b.beds.reduce((n:number,b:any)=>n+b.count*b.placesPerBed,0),4);assert.equal(b.unitsOffered,undefined);});
test('OR32 property-wide availability cannot supply exact-offer bookability',async()=>{const x=await fixture();x.n.offers[0].availability.bookability.applicability='PROPERTY_WIDE';const a=x.prepare();assert.equal(a.input,null);assert.equal(a.assessment.offers[0].availability.bridgeBoolean,null);});
test('OR33 rating scale and hotel-level tax fallback cannot promote missing evidence',async()=>{const x=await fixture();x.n.offers[0].ratingScale.value=5;assert.throws(x.run,/RATING_OUTSIDE/);x.n.offers[0].ratingScale.value=20;assert.throws(x.prepare,/RATING_NORMALIZATION/);x.n.offers[0].ratingScale.value=10;state(x.n.offers[0].completeTotal,'UNKNOWN');const h=x.b.search.hotels[0];h.totalKnownCost=null;h.offers[0].totalKnownCost=null;h.offers[0].taxesIncluded=null;assert.throws(x.prepare,/TOTAL_PROMOTION/);});
test('OR34 supported family input retains party counts and output through actual bridge',async()=>{const x=await fixture();family(x);const a=x.prepare();assert.equal(a.status,'SUPPORTED_DIAGNOSTIC_INPUT');assert.deepEqual(runIntentRolePolicyBridgeV3(a.input),runIntentRolePolicyBridgeV3(x.b));assert.deepEqual(a.separatelyEvaluatedParty.childAgesAtStay,[8,13]);assert.equal(a.input.search.children,2);assert.equal(a.input.search.adults,2);});
