import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
const load=new Function('p','return import(p)') as (p:string)=>Promise<any>;
async function fixture(){
 const d=await load(pathToFileURL(join(process.cwd(),'scripts/diagnostic-transcription-review-v1.mjs')).href);
 const bridge=await load(pathToFileURL(join(process.cwd(),'scripts/diagnostic-role-feedback-bridge-v1.mjs')).href);
 const H='a'.repeat(64),value=(v:any)=>({status:v===null?'UNKNOWN':'KNOWN',value:v,reliability:v===null?'UNKNOWN':'LOW',reason:v===null?'Not documented':null,unknownReason:v===null?'Not documented':null,evidenceRefs:['P']});
 const packet:any={schemaVersion:d.VERSION,caseId:'SYNTHETIC_FEEDBACK',mode:'SYNTHETIC_TEST',classification:'DIAGNOSTIC_ONLY',humanReview:'PENDING',custodyCreated:false,sourceArchiveSha256:H,proofs:[{ref:'P',sha256:H,path:'p.png'}],scenario:{currency:'EUR'},alternatives:Array.from({length:5},(_,i)=>({id:'SYNTHETIC_'+i,proofs:[],fields:Object.entries({completeTotal:null,ratingScale:null,distance:i===1?'3,8 km dal centro':'600 m dal centro',displayedPrice:1500,mealPlan:'Only room',advertising:true}).map(([key,v])=>({key,label:key,critical:['completeTotal','ratingScale'].includes(key),value:value(v),reviewStatus:'PENDING',sourceKind:v===null?'UNKNOWN':'OBSERVED'}))}))};
 let state=d.initialReview(packet,H);const events:any[]=[];
 const append=(action:any)=>{const a={...action,caseId:packet.caseId,expectedRevision:state.revision,contentFingerprint:d.fingerprint(state)};const body={schemaVersion:d.VERSION,ordinal:state.revision+1,packetHash:state.packetHash,codeHash:H,previousHash:state.lastEventHash,recordedAt:'2026-09-08T00:00:00.000Z',actor:'SYNTHETIC_TEST',action:a};const event={...body,eventHash:d.sha256(d.json(body))};state=d.applyReview(state,a,packet);state.lastEventHash=event.eventHash;events.push(event);};
 for(const alt of packet.alternatives)for(const f of alt.fields)append({type:'REVIEW_FIELD',alternativeId:alt.id,fieldKey:f.key,reviewStatus:'CORRECT'});
 append({type:'CONFIRM_REVIEW',confirmed:true});
 const feedback:any={documentType:'ASSISTANT_RECORD_OF_USER_DIAGNOSTIC_ROLE_FEEDBACK',noteRevision:2,activeInterpretation:true,classification:'DIAGNOSTIC_ONLY',caseId:packet.caseId,roleLabelsAreUserFeedbackNotEngineOutput:true,sourceBinding:{sourceFinalArchiveSha256:H,sourcePacketSha256:state.packetHash,sourceCodeManifestSha256:H,sourceReviewLastEventHash:state.lastEventHash,sourceContentFingerprint:d.fingerprint(state),sourceReviewRevision:state.revision,sourceReviewStatus:state.humanReview,originalScenarioManifestSha256:H},scope:{variantsFormulatedAfterObservingOffers:true,originalScenarioModified:false,independentBlindJudgment:false,goldenAdmission:false},distancePolicyAsClarifiedByUser:{numericExceptionTolerance:null},supersedes:{noteRevision:1,archiveSha256:H},bestChoiceAcrossTheTwoStatedDistanceVariants:{alternativeId:'SYNTHETIC_0'},scenarioRoleAssignments:[{distanceReferenceKm:1,bestChoice:{alternativeId:'SYNTHETIC_0'},bestOverBudget:null,bestOverBudgetStatus:'NOT_ASSIGNED_BY_USER_FOR_THIS_VARIANT'},{distanceReferenceKm:3,bestChoice:{alternativeId:'SYNTHETIC_0'},bestOverBudget:{alternativeId:'SYNTHETIC_1'}}],assistantFactualNotes:[{evidenceRefs:['P']}]};
 const args:any={packet,events,codeHash:H,reviewArchiveSha256:H,feedback,feedbackSha256:d.sha256(d.json(feedback)),originalManifestSha256:H,budgetMinorUnits:140000,currency:'EUR'};
 return {bridge,d,args,append,run:()=>bridge.prepareDiagnosticRoleFeedback(args),rehash:()=>args.feedbackSha256=d.sha256(d.json(args.feedback))};
}
test('RF01 verified complete chain and final confirmation; deterministic preparation does not mutate inputs',async()=>{const x=await fixture(),before=JSON.stringify(x.args),a=x.run();assert.deepEqual(a,x.run());assert.equal(JSON.stringify(x.args),before);assert.equal(a.prerequisites.transcriptionConfirmed,true);});
test('RF02 UNKNOWN survives and displayed price never fills complete total or rating scale',async()=>{const x=await fixture(),a=x.run();assert.equal(a.missingness.length,10);for(const alt of a.diagnosticInput.alternatives){assert.equal(alt.fields.find((f:any)=>f.key==='completeTotal').value.value,null);assert.equal(alt.priceClaims.exactBookable,false);}assert.equal(a.prerequisites.comparisonExecutable,false);});
test('RF03 R2 supersedes R1, one case two post-observation variants, no Golden/blind/expert',async()=>{const a=(await fixture()).run();assert.equal(a.feedbackRecord.caseCount,1);assert.equal(a.feedbackRecord.variantCount,2);assert.equal(a.feedbackRecord.noteRevision,2);assert.equal(a.feedbackRecord.blind,false);assert.equal(a.feedbackRecord.expert,false);assert.equal(a.prerequisites.goldenAdmission,false);assert(a.diagnosticInput.postObservationContexts.every((v:any)=>!v.prospectivelyFrozen&&!v.independentCase));});
test('RF04 3.8 km preserved; 0.8 deviation not global tolerance or hard maximum',async()=>{const a=(await fixture()).run();assert.equal(a.feedbackRecord.assignments[1].overBudgetDistanceDeviationKm,0.8);assert.equal(a.diagnosticInput.postObservationContexts[1].distancePreference.generalToleranceKm,null);assert.equal(a.diagnosticInput.postObservationContexts[1].distancePreference.hardMaximum,false);});
test('RF05 feedback choices excluded from preparatory input and fingerprint',async()=>{const x=await fixture(),before=x.run();x.args.feedback.bestChoiceAcrossTheTwoStatedDistanceVariants.alternativeId='SYNTHETIC_2';for(const v of x.args.feedback.scenarioRoleAssignments)v.bestChoice.alternativeId='SYNTHETIC_2';x.rehash();assert.deepEqual(x.run().diagnosticInput,before.diagnosticInput);assert.equal(x.run().diagnosticInputFingerprint,before.diagnosticInputFingerprint);});
test('RF06 tampered event rejected',async()=>{const x=await fixture();x.args.events[0].recordedAt='2026-09-09T00:00:00Z';assert.throws(x.run,/HISTORY_INVALID/);});
test('RF07 missing final confirmation rejected',async()=>{const x=await fixture();x.args.events.pop();assert.throws(x.run,/NOT_CONFIRMED/);});
test('RF08 later correction invalidates confirmation',async()=>{const x=await fixture();x.append({type:'REVIEW_FIELD',alternativeId:'SYNTHETIC_0',fieldKey:'mealPlan',reviewStatus:'CORRECT'});assert.throws(x.run,/NOT_CONFIRMED/);});
test('RF09 mismatched reviewed fingerprints or source archive rejected',async()=>{for(const key of ['sourceContentFingerprint','sourceFinalArchiveSha256','sourcePacketSha256','sourceCodeManifestSha256','sourceReviewLastEventHash','originalScenarioManifestSha256']){const x=await fixture();x.args.feedback.sourceBinding[key]='b'.repeat(64);x.rehash();assert.throws(x.run,/BINDING_MISMATCH/);}});
test('RF10 unknown alternative, missing proof reference and contradictory roles rejected',async()=>{for(const kind of ['alt','proof','role']){const x=await fixture();if(kind==='alt')x.args.feedback.scenarioRoleAssignments[1].bestOverBudget.alternativeId='MISSING';if(kind==='proof')x.args.feedback.assistantFactualNotes[0].evidenceRefs=['ABSENT'];if(kind==='role')x.args.feedback.scenarioRoleAssignments[0].bestChoice.alternativeId='SYNTHETIC_3';x.rehash();assert.throws(x.run);}});
test('RF11 unassigned over-budget is not abstention; role has no automatic upgrade mapping',async()=>{const a=(await fixture()).run();assert.equal(a.feedbackRecord.assignments[0].bestOverBudget,null);assert.equal(a.feedbackRecord.assignments[0].bestOverBudgetStatus,'NOT_ASSIGNED_BY_USER_FOR_THIS_VARIANT');assert.equal(a.feedbackRecord.assignments[1].engineRoleMapping.bestOverBudget,null);assert.equal(a.feedbackRecord.engineOutput,null);});
test('RF12 no reclassification, invalid budget or R1 accepted',async()=>{for(const kind of ['r1','blind','tolerance','budget']){const x=await fixture();if(kind==='r1')x.args.feedback.noteRevision=1;if(kind==='blind')x.args.feedback.scope.independentBlindJudgment=true;if(kind==='tolerance')x.args.feedback.distancePolicyAsClarifiedByUser.numericExceptionTolerance=1;if(kind==='budget')x.args.budgetMinorUnits=NaN;x.rehash();assert.throws(x.run);}});
test('RF13 distance landmarks/ranges are not centre distance',async()=>{const x=await fixture();for(const v of ['250 m da Piazza Grande','circa 3 km dal centro','3-4 km dal centro'])assert.equal(x.bridge.observedCenterDistanceKm({status:'KNOWN',value:v}),null);assert.equal(x.bridge.observedCenterDistanceKm({status:'KNOWN',value:'600 m dal centro'}),0.6);});
test('RF14 tampered feedback hash rejected before preparing inputs',async()=>{const x=await fixture();x.args.feedback.noteRevision=1;assert.throws(x.run,/CONTENT_HASH_MISMATCH/);});
test('RF15 audit fields excluded from diagnostic feature preparation, observations retained',async()=>{const a=(await fixture()).run();assert(!a.diagnosticInput.alternatives[0].fields.some((f:any)=>f.key==='advertising'));assert(a.reviewedObservations[0].fields.some((f:any)=>f.key==='advertising'));});
test('RF16 boundary imports no engine, transport, filesystem writer or custody',()=>{const code=readFileSync(join(process.cwd(),'scripts/diagnostic-role-feedback-bridge-v1.mjs'),'utf8');assert.doesNotMatch(code,/from ['"](?:node:fs|node:http|.*adapter\/|.*custody)/);assert.doesNotMatch(code,/\bfetch\s*\(|writeFileSync|startReview\s*\(/);});

test('RF17 critical transcription findings do not claim unexecuted engine rejection',async()=>{const a=(await fixture()).run();assert.equal(a.prerequisites.assessmentVersion,'stayopti.diagnostic-prerequisite-assessment@2');assert.equal(a.prerequisites.transcriptionCompletenessFindings.length,10);assert.deepEqual(a.prerequisites.dataBlockers,[]);assert.equal(a.prerequisites.dataBlockerAssessment,'NOT_EXECUTED_ON_CANONICAL_REAL_INPUT');assert.equal(a.prerequisites.engineExecuted,false);});
test('RF18 unmapped over-budget role does not itself block Best Choice-only comparison',async()=>{const a=(await fixture()).run();assert.equal(a.prerequisites.roleCoverage.bestOverBudget,'UNMAPPED_NOT_A_BLOCKER_FOR_BEST_CHOICE_ONLY');assert(!a.prerequisites.softwareBlockers.includes('BEST_OVER_BUDGET_IS_NOT_CANONICAL_V3_ROLE'));assert.equal(a.prerequisites.roleCoverage.fullRoleComparisonExecutable,false);assert.equal(a.prerequisites.comparisonExecutable,false);assert.equal(a.feedbackRecord.engineOutput,null);});
test('RF19 synthetic capability results never authorize real execution or Golden',async()=>{const a=(await fixture()).run();assert.equal(a.prerequisites.verifiedSyntheticCapabilities.realCaseExecutionInferred,false);assert.equal(a.prerequisites.goldenAdmission,false);assert.equal(a.prerequisites.blindEligibility,false);assert(a.prerequisites.softwareBlockers.includes('POSTHOC_SOFT_DISTANCE_POLICY_MAPPING_NOT_VALIDATED'));});
