import assert from 'node:assert/strict';
import test from 'node:test';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {fixture,reviewedFixture} from './fixtures/observedOfferRequirementsSyntheticV3';
import {computeObservedOfferDiagnosticV3} from '../../src/engine-v3/evaluation/observedOfferDiagnosticV3';
import {runIntentRolePolicyBridgeV3} from '../../src/engine-v3/evaluation/intentRolePolicyBridgeV3';
import {evaluateSmartStaySearchV2} from '../../src/engine-v2/orchestrator/smartStayEngineV2';
const load=new Function('p','return import(p)') as (p:string)=>Promise<any>;
const unknown=(c:any)=>Object.assign(c,{state:'UNKNOWN',value:null});
async function control(profile='balanced'){
  const x=await fixture(),m=await load(pathToFileURL(join(process.cwd(),'scripts/observed-offer-execution-v1.mjs')).href);
  // Explicitly reported distances, no computed geographic reconciliation in
  // either control. This is a legitimate complete old-bridge input.
  for(const h of x.b.search.hotels){h.latitude=null;h.longitude=null;h.availableData.hasCoordinates=false;}
  x.b.search.preferenceId=profile;
  const previous=evaluateSmartStaySearchV2(x.b.search);
  const request:any={kind:'SYNTHETIC',normalization:x.n,contextId:'PREFERENCE',syntheticRequirementBasis:structuredClone(x.n.party.requirements),
    syntheticQuery:{...x.b.search,childAgesAtStay:[],destinationKey:x.b.search.destinationKey??x.b.search.selectedLocation?.label??null,preferenceSource:'manual'},
    syntheticSignals:previous.evaluations.map(e=>({alternativeId:e.hotel.id,evidence:structuredClone(e.evidence),features:[...e.hotel.amenities,...e.hotel.facilities],
      roomText:e.hotel.offers[0].roomName,category:null,observations:{synthetic:true},provenance:{kind:'SYNTHETIC'}}))};
  delete request.syntheticQuery.hotels;
  return {x,m,request,previous,run:()=>m.executeObservedOfferDiagnostic(request,computeObservedOfferDiagnosticV3)};
}
const scores=(r:any)=>r.output.candidates.map((c:any)=>({id:c.hotelId,dimensions:Object.fromEntries(Object.entries(c.policy.dimensions).map(([k,v]:any)=>[k,v.score]))}));
test('OD01 complete explicit input reaches unchanged policy and preserves previous numeric dimensions',async()=>{
  const f=await control(),r=f.run(),old=runIntentRolePolicyBridgeV3(f.x.b);
  assert.equal(r.output.policyExecuted,true);assert.equal(r.output.decision.status,'usable');
  assert.deepEqual(scores(r),old.candidates.map(c=>({id:c.hotelId,dimensions:Object.fromEntries(Object.entries(c.policy.dimensions).map(([k,v])=>[k,v.score]))})));
  const ids=(selection:any)=>selection.equivalentSolutionIds.map((id:string)=>r.output.candidates.find((c:any)=>c.policy.solutionId===id)?.hotelId).sort();
  const oldIds=(selection:any)=>selection.equivalentSolutionIds.map((id:string)=>old.candidates.find(c=>c.policy.solutionId===id)?.hotelId).sort();
  for(const role of Object.keys(old.decision.portfolio))assert.deepEqual(ids(r.output.decision.portfolio[role]),oldIds((old.decision.portfolio as any)[role]));
});
test('OD02 documented common source centre calculates location without coordinates or equivalence',async()=>{const f=await control();const ref={kind:'SOURCE_CENTRE',id:'SOURCE_CENTRE',point:null,provenance:'Documented synthetic centre'};f.x.n.geography.commonReference.value=ref;for(const o of f.x.n.offers)o.reference.value=ref;const r=f.run();assert(r.output.candidates.every((c:any)=>c.calculated.location.score!==null&&c.calculated.location.distance.source==='documented-reference'));assert(r.r1Assessment.offers.every((o:any)=>o.geography.selectedLocationEquivalenceVerified===false));assert(r.input.candidates.every((c:any)=>!c.facts.some((f:any)=>f.code==='location.coordinates')));});
test('OD03 incompatible and unverified reference remains retained, unscored and unpreferred',async()=>{for(const k of ['different','unverified']){const f=await control();if(k==='different')f.x.n.offers[0].reference.value={...f.x.n.offers[0].reference.value,id:'OTHER'};else f.x.n.offers[0].distanceKm.applicability='UNVERIFIED';const r=f.run(),c=r.output.candidates[0];assert.equal(c.policy.dimensions.location.score,null);assert.equal(c.distance.status,'unknown');assert.notEqual(c.policy.contextualEligibility.status,'eligible');assert.equal(r.output.candidates.length,3);}});
test('OD04 observed availability and UNKNOWN cannot lower factual quality or become bookable',async()=>{for(const observed of [true,false]){const f=await control(),before=scores(f.run());for(const o of f.x.n.offers){unknown(o.availability.bookability);if(!observed)unknown(o.availability.observed);}const r=f.run();assert.deepEqual(scores(r),before);assert(r.input.candidates.every((c:any)=>c.facts.find((f:any)=>f.code==='offer.bookable').value===null));assert.equal(r.output.decision.status,'abstained');assert.equal(r.output.policyExecuted,true);}});
test('OD05 best apparent incomplete stays in output; complete peers can be recommended',async()=>{const f=await control();unknown(f.x.n.offers[0].completeTotal);const r=f.run();assert.equal(r.output.candidates.length,3);assert.equal(r.output.candidates[0].policy.totalCost,null);assert(!r.output.decision.portfolio.bestChoice.equivalentSolutionIds.includes(r.output.candidates[0].policy.solutionId));assert.equal(r.output.policyExecuted,true);});
test('OD06 all incomplete totals produce actual policy abstention, with dimensions, not preparer abort',async()=>{const f=await control();for(const o of f.x.n.offers)unknown(o.completeTotal);const r=f.run();assert.equal(r.output.policyExecuted,true);assert.equal(r.output.decision.status,'abstained');assert(r.output.candidates.every((c:any)=>c.dimensionsCalculated.includes('location')&&c.policy.totalCost===null));assert.equal(r.output.fullRobustness,'NOT_EXECUTED');});
for(const kind of ['insufficient','violation','conflict'])test('OD07 accommodation '+kind+' retained and not recommended',async()=>{const f=await control(),o=f.x.n.offers[0];if(kind==='insufficient')unknown(o.sleeping);if(kind==='violation')o.capacityGuests.value=1;if(kind==='conflict')Object.assign(o.capacityGuests,{state:'CONFLICTING',value:null});const r=f.run();assert.equal(r.output.candidates.length,3);assert.notEqual(r.output.candidates[0].policy.hardConstraintsSatisfied,true);assert(!r.output.decision.portfolio.bestChoice.equivalentSolutionIds.includes(r.output.candidates[0].policy.solutionId));});
test('OD08 unnormalizable rating is omitted; observation retained and computation proceeds',async()=>{const f=await control();for(const o of f.x.n.offers)unknown(o.ratingScale);const r=f.run();assert(r.input.candidates.every((c:any)=>c.facts.find((f:any)=>f.code==='review.score').value===null));assert(r.r1Assessment.offers.every((o:any)=>o.rating.observation.value!==null));assert.equal(r.output.policyExecuted,true);});
test('OD09 applicability R1 remains enforced for total, source distance and rating',async()=>{for(const k of ['UNVERIFIED','PROPERTY_WIDE']){const f=await control();f.x.n.offers[0].completeTotal.applicability=k;f.x.n.offers[0].distanceKm.applicability='UNVERIFIED';const r=f.run();assert.equal(r.input.candidates[0].assessment.completeTotal,null);assert.equal(r.output.candidates[0].policy.dimensions.location.score,null);assert(r.output.candidates[0].assessment.recommendationBlockers.includes('COMPLETE_TOTAL_APPLICABILITY_UNVERIFIED'));}});
test('OD10 availability conflicting/unavailable differs from UNKNOWN, never property quality penalty',async()=>{const f=await control(),before=scores(f.run());f.x.n.offers[0].availability.unavailable.state='KNOWN';f.x.n.offers[0].availability.unavailable.value=true;const r=f.run();assert.equal(r.output.candidates[0].assessment.availability,'CONFLICTING');assert.equal(r.output.candidates[0].policy.offerIntegrity,'invalid');assert.deepEqual(scores(r),before);});
test('OD11 identity, provider, order and feedback do not select the winner',async()=>{const f=await control(),r=f.run();f.request.feedback={winner:'synthetic-other'};for(const s of f.request.syntheticSignals){s.provider='OTHER';s.name='OTHER NAME';s.provenance.provider='OTHER';}f.x.n.offers.reverse();f.request.syntheticSignals.reverse();const z=f.run();assert.deepEqual([...scores(z)].sort((a,b)=>a.id.localeCompare(b.id)),[...scores(r)].sort((a,b)=>a.id.localeCompare(b.id)));assert.deepEqual(z.output.decision.portfolio,r.output.decision.portfolio);});
test('OD12 source and query cannot be altered through caller gate/result suggestions',async()=>{const f=await control();unknown(f.x.n.offers[0].completeTotal);f.request.assessment={completeTotal:1,bookability:true};f.request.essentialCoverage='ALL_PASS';assert.equal(f.run().input.candidates[0].assessment.completeTotal,null);f.request.syntheticRequirementBasis.capacity=false;assert.throws(f.run,/ESSENTIAL_BASIS_MISMATCH/);});
test('OD13 reviewed entry consumes R1 coverage and confirmed journal rather than caller flags',async()=>{const f=await reviewedFixture(),m=await load(pathToFileURL(join(process.cwd(),'scripts/observed-offer-execution-v1.mjs')).href);const run=()=>m.executeObservedOfferDiagnostic({kind:'REVIEWED',reviewed:f.args,normalization:f.n,contextId:'PREFERENCE'},computeObservedOfferDiagnosticV3);assert.equal(run().reviewedBinding.reviewConfirmed,true);for(const k of Object.keys(f.n.party.requirements))f.n.party.requirements[k]=false;for(const mapping of f.n.requirementMapping)mapping.needIndexes=[];unknown(f.n.offers[0].sleeping);unknown(f.n.offers[0].capacityGuests);assert.throws(run,/ESSENTIAL_REQUIREMENT_COVERAGE/);});
test('OD14 unrepresented essential need executes no decision, not labelled V3 abstention',async()=>{const f=await reviewedFixture({needs:[{requirement:'Invented unsupported sensory requirement',essential:true}]}),m=await load(pathToFileURL(join(process.cwd(),'scripts/observed-offer-execution-v1.mjs')).href);for(const r of f.n.requirementMapping){r.needIndexes=[];f.n.party.requirements[r.key]=false;}const r=m.executeObservedOfferDiagnostic({kind:'REVIEWED',reviewed:f.args,normalization:f.n,contextId:'PREFERENCE'},computeObservedOfferDiagnosticV3);assert.equal(r.output.policyExecuted,false);assert.equal(r.output.decision,null);assert.equal(r.output.inputStatus,'NON_REPRESENTABLE_ESSENTIAL_REQUIREMENT');});
test('OD15 reviewed normalization counterexample is rejected before computation',async()=>{const f=await reviewedFixture(),m=await load(pathToFileURL(join(process.cwd(),'scripts/observed-offer-execution-v1.mjs')).href);f.n.offers[0].capacityGuests.value=0;let calls=0;assert.throws(()=>m.executeObservedOfferDiagnostic({kind:'REVIEWED',reviewed:f.args,normalization:f.n,contextId:'PREFERENCE'},()=>{calls++;}),/CAPACITY_NORMALIZATION_CHANGED/);assert.equal(calls,0);});
test('OD16 reviewed material cannot be rerouted to synthetic lower evaluator',async()=>{const f=await reviewedFixture(),m=await load(pathToFileURL(join(process.cwd(),'scripts/observed-offer-execution-v1.mjs')).href);assert.throws(()=>m.executeObservedOfferDiagnostic({kind:'SYNTHETIC',normalization:f.n},computeObservedOfferDiagnosticV3),/SYNTHETIC_CANNOT_REPLACE_REVIEWED_ENTRY/);});
for(const profile of ['maximum-comfort','comfort','savings','maximum-savings'])test('OD17 complete parity profile '+profile,async()=>{const f=await control(profile),r=f.run(),old=runIntentRolePolicyBridgeV3(f.x.b);assert.deepEqual(scores(r),old.candidates.map(c=>({id:c.hotelId,dimensions:Object.fromEntries(Object.entries(c.policy.dimensions).map(([k,v])=>[k,v.score]))})));assert.equal(r.output.decision.status,old.decision.status);const ids=r.output.decision.portfolio.bestChoice.equivalentSolutionIds.map((id:string)=>r.output.candidates.find((c:any)=>c.policy.solutionId===id).hotelId).sort();assert.deepEqual(ids,old.decision.portfolio.bestChoice.equivalentSolutionIds.map(id=>old.candidates.find(c=>c.policy.solutionId===id)!.hotelId).sort());});
test('OD18 family, two internal rooms in one unit and sofa/bunk unknowns traverse actual policy',async()=>{for(const kind of ['complete','sofa','bunk']){const f=await control();f.x.n.party.childAgesAtStay=[7,12];f.x.n.party.requirements.childAdmission=true;f.request.syntheticRequirementBasis.childAdmission=true;f.request.syntheticQuery.childAgesAtStay=[7,12];f.request.syntheticQuery.children=2;for(const o of f.x.n.offers){o.scope.party.childAgesAtStay=[7,12];o.capacityGuests.value=4;o.internalRooms.value=2;Object.assign(o.children.admitted,{state:'KNOWN',value:true});Object.assign(o.children.adultPricingFromAge,{state:'KNOWN',value:6});o.sleeping.value.beds=[{kind:'DOUBLE',count:2,placesPerBed:2,placeBasis:'Two documented double beds'}];if(kind!=='complete')o.sleeping.value.beds=[{kind:kind.toUpperCase(),count:2,placesPerBed:null,placeBasis:'Places undocumented'}];}const r=f.run();assert.equal(r.output.policyExecuted,true);assert.deepEqual(r.output.party.childAgesAtStay,[7,12]);assert.equal(r.output.party.adults,2);assert(r.r1Assessment.offers.every((o:any)=>o.accommodation.units.status==='SATISFIED'&&o.accommodation.internalRooms.value===2));if(kind!=='complete'){assert.equal(r.output.decision.status,'abstained');assert(r.r1Assessment.offers.every((o:any)=>o.accommodation.sleeping.status==='INSUFFICIENT_INFORMATION'));}}});
test('OD19 explicitly accepted distance gain reuses proof guard; no implicit tolerance',async()=>{const f=await control();f.request.distanceException={hotelId:f.x.n.offers[2].alternativeId,comparedWithHotelId:f.x.n.offers[0].alternativeId,dimension:'quality',reason:'EXPLICIT_EXPERIENCE_GAIN_ACCEPTED',evidenceIds:['fabricated']};assert.throws(f.run,/DISTANCE_EXCEPTION_UNSUPPORTED/);});
test('OD20 bounded source text extensions preserve counts and reject contradiction, no unknown promotion',async()=>{const f=await reviewedFixture({fields:{roomCapacity:'2 persone; ideale per 1 adulti e 1 bambini',childrenPolicy:'Da 7 anni pagano come adulti; nessun letto supplementare disponibile.'}});const normalizer=f.v2;assert.equal(normalizer.normalizedCount('2 persone; ideale per 1 adulti e 1 bambini','capacity'),2);assert.equal(normalizer.normalizedCount('2 persone; ideale per 3 adulti e 1 bambini','capacity'),null);assert.deepEqual(normalizer.suiteCounts('Una suite privata con tre camere interne, un matrimoniale e cinque singoli; capienza sette dichiarata.'),{unitsOffered:1,internalRooms:3});assert.equal(normalizer.suiteCounts('Una suite privata con tre camere interne oppure due unità'),null);const c=f.n.offers[0].children;Object.assign(c.adultPricingFromAge,{state:'KNOWN',value:7});c.adultPricingFromAge.links[0].field='childrenPolicy';Object.assign(c.extraBedsAvailable,{state:'KNOWN',value:false});c.extraBedsAvailable.links[0].field='childrenPolicy';assert.doesNotThrow(f.run);c.adultPricingFromAge.value=8;assert.throws(f.run,/CHILD_PRICING_NORMALIZATION_CHANGED/);});
test('OD21 qualified child-price rule is not an admission certificate',async()=>{const f=await reviewedFixture();const c=f.v2.childFacts('Da 16 anni pagano come adulti; per minori selezionare tariffa con condizioni esplicite.');assert.equal(c.adultPricingFromAge,16);assert.equal(c.admitted,null);assert.equal(c.minimumAge,null);assert.equal(f.v2.childFacts('Da 16 anni pagano come adulti, ma non per questa offerta'),null);});
test('OD22 names of accommodation cannot create category fit or unit privacy',async()=>{const f=await control(),r=f.run();for(const s of f.request.syntheticSignals){s.name='Private luxury hotel';s.provider='lowest-id';}const z=f.run();assert.deepEqual(z.output.decision,r.output.decision);});
test('OD23 all input observations remain byte-identical after computation',async()=>{const f=await control();unknown(f.x.n.offers[0].completeTotal);unknown(f.x.n.offers[1].ratingScale);const before=JSON.stringify(f.request);f.run();assert.equal(JSON.stringify(f.request),before);});
test('OD24 bounded coherent accommodation wording retains essential sleeping and capacity only',async()=>{const f=await reviewedFixture({needs:[{requirement:'Configurazione e posti letto adeguati per tutti gli ospiti',essential:true}]});const r=f.run();assert.equal(r.essentialRequirementCoverage.status,'ESSENTIAL_COVERAGE_DEFINED');assert.deepEqual(r.essentialRequirementCoverage.needs[0].checks,['sleepingPlaces','capacity']);assert.equal(r.party.requirements.privateBathroom,false);assert.equal(r.party.requirements.childAdmission,false);});

test('OD25 child-admission qualification is not lost by clause order',async()=>{const f=await reviewedFixture();for(const text of ['Per minori selezionare tariffa con condizioni esplicite; bambini di tutte le età ammessi','Bambini di tutte le età ammessi; per minori selezionare tariffa con condizioni esplicite']){const c=f.v2.childFacts(text);assert.equal(c.admitted,null);assert.equal(c.minimumAge,null);}});

test('OD26 automatic intent control uses the same supported policy profile',async()=>{const f=await control();f.x.b.profileOrigin='automatic';f.x.b.search.preferenceSource='automatic';f.request.syntheticQuery.preferenceSource='automatic';const r=f.run(),old=runIntentRolePolicyBridgeV3(f.x.b);assert.equal(r.output.profile.effectivePreferenceId,old.profile.effectivePreferenceId,JSON.stringify({actual:r.output.profile,previous:old.profile}));assert.equal(r.output.decision.status,old.decision.status);});
