export {
  adaptV2SearchResultToDecisionV3,
  type AdaptV2SearchResultToDecisionV3Input,
  type StayOptiV3CompatibilityPolicyInput,
} from "./adapter/v2CompatibilityAdapterV3";

export {
  assertCommercialFirewallV3,
  evaluateCommercialFirewallV3,
  type SmartStayCommercialFirewallEvaluationV3,
  type SmartStayCommercialFirewallViolationV3,
} from "./contract/commercialFirewallV3";

export {
  assertStayOptiDecisionV3,
  validateStayOptiDecisionV3,
  type StayOptiDecisionCandidateV3,
  type StayOptiDecisionContextV3,
  type StayOptiDecisionIntegrityV3,
  type StayOptiDecisionPersonalizationV3,
  type StayOptiDecisionRoleV3,
  type StayOptiDecisionStatusV3,
  type StayOptiDecisionThesisV3,
  type StayOptiDecisionV3,
} from "./contract/stayOptiDecisionV3";

export {
  assertStaySolutionV3,
  validateStaySolutionV3,
  type StaySolutionCostV3,
  type StaySolutionSegmentV3,
  type StaySolutionV3,
} from "./contract/staySolutionV3";

export {
  createStableHashV3,
  stableSerializeV3,
} from "./contract/stableHashV3";

export {
  SMARTSTAY_REASON_CODES_V3,
  type SmartStayReasonCodeV3,
} from "./contract/reasonCodesV3";

export {
  SMARTSTAY_V3_VERSIONS,
} from "./contract/versionsV3";

export {
  createStayIntegrityCoverageReportV3,
  type StayIntegrityCoverageReportV3,
  type StayIntegrityGateStatusV3,
  type StayPublicRatesConsistencyV3,
} from "./integrity/integrityCoverageV3";

export {
  assertStayOfferIntegritySnapshotV3,
  createCanonicalOfferKeyV3,
  createStayOfferIntegritySnapshotV3,
  createStayOfferSnapshotFingerprintV3,
  deduplicateStayOfferSnapshotsV3,
  enumerateStayNightsV3,
  parseIsoDateV3,
  validateStayOfferIntegritySnapshotV3,
  type CreateStayOfferIntegritySnapshotInputV3,
  type StayCanonicalCostV3,
  type StayNightEvidenceInputV3,
  type StayOfferIntegritySnapshotV3,
  type StayScopeV3,
  type StayTemporalPriceEvidenceV3,
} from "./integrity/stayOfferIntegrityV3";

export {
  compareStayOfferRecheckV3,
  type StayOfferRecheckDecisionDiffV3,
  type StayOfferRecheckStateV3,
} from "./integrity/recheckDecisionDiffV3";

export {
  createDecisionFingerprintV3,
  runDeterministicDecisionReplayV3,
  verifyDecisionReplayV3,
} from "./replay/decisionReplayV3";

export {
  STAYOPTI_INDEPENDENT_DECISION_AUDIT_V3,
  STAYOPTI_PUBLIC_RATE_MAX_DELTA_V3,
  createBoundPublicRateAbstentionEvidenceV3,
  createBoundPublicRateEvidenceV3,
  createHotelSelectionTokenV3,
  createIndependentV3ComparableDecisionV3,
  createV2ComparableDecisionV3,
  deriveBoundPublicRateConsistencyV3,
  deriveIndependentShadowSafetySignalsV3,
  runIndependentDecisionShadowV3,
  type RunIndependentDecisionShadowInputV3,
  type RunIndependentDecisionShadowResultV3,
  type StayOptiBoundPublicRateAbstentionEvidenceV3,
  type StayOptiBoundPublicRateEvidenceV3,
  type StayOptiBoundPublicRateEvidenceInputV3,
} from "./orchestrator/independentDecisionEngineV3";

export {
  STAYOPTI_FRONTEND_SHADOW_RUNTIME_AUDIT_V3,
  deriveFrontendShadowSegmentV3,
  readFrontendShadowBufferV3,
  resetFrontendShadowBufferV3,
  runFrontendIndependentShadowRuntimeV3,
  type RunFrontendIndependentShadowRuntimeInputV3,
  type StayOptiFrontendShadowRuntimeModeV3,
} from "./runtime/frontendIndependentShadowRuntimeV3";

export {
  applyDiminishingReturnsV3,
  createBudgetUtilityV3,
  evaluatePersonalUtilityV3,
  isStayOptiPreferenceIdV3,
  resolvePersonalPreferenceV3,
  validatePersonalUtilityEvaluationV3,
  type EvaluateStayOptiPersonalUtilityInputV3,
  type StayOptiPersonalUtilityContextV3,
  type StayOptiPersonalUtilityEvaluationV3,
  type StayOptiPreferenceIdV3,
  type StayOptiPreferenceOriginV3,
  type StayOptiPreferenceResolutionV3,
  type StayOptiTripTypeV3,
  type StayOptiUtilityContributionV3,
  type StayOptiUtilityDimensionInputV3,
  type StayOptiUtilityDimensionV3,
  type StayOptiUtilityInteractionV3,
} from "./utility/personalUtilityV3";

export {
  evaluatePeerIntelligenceV3,
  validatePeerAssignmentV3,
  type StayOptiPeerAssignmentV3,
  type StayOptiPeerCandidateV3,
  type StayOptiPeerCategoryV3,
  type StayOptiPeerExclusionV3,
  type StayOptiPeerGroupModeV3,
  type StayOptiPeerIntelligenceOptionsV3,
  type StayOptiPeerUnitTypeV3,
} from "./peer/peerIntelligenceV3";

export {
  STAYOPTI_GEOMETRY_BENEFIT_DIMENSIONS_V3,
  assertDecisionGeometryV3,
  evaluateDecisionGeometryV3,
  validateDecisionGeometryV3,
  type EvaluateStayOptiDecisionGeometryCandidateV3,
  type StayOptiDecisionGeometryOptionsV3,
  type StayOptiDecisionGeometryV3,
  type StayOptiDecisionMapPointV3,
  type StayOptiDecisionMapZoneV3,
  type StayOptiDominanceKindV3,
  type StayOptiDominanceRelationV3,
  type StayOptiGeometryBenefitDimensionV3,
  type StayOptiGeometryCandidateEvaluationV3,
  type StayOptiGeometryCandidateStatusV3,
  type StayOptiGeometryDimensionV3,
  type StayOptiMarginalTrendV3,
  type StayOptiMarginalValueSegmentV3,
  type StayOptiMaximumSensiblePriceV3,
  type StayOptiPairwiseComparisonV3,
  type StayOptiPairwiseOutcomeV3,
  type StayOptiParetoStatusV3,
  type StayOptiThresholdResolutionStatusV3,
  type StayOptiThresholdVerdictV3,
  type StayOptiTradeOffThresholdV3,
} from "./geometry/decisionGeometryV3";

export {
  STAYOPTI_ROBUSTNESS_SCENARIOS_V3,
  assertDecisionRobustnessV3,
  evaluateDecisionRobustnessV3,
  validateDecisionRobustnessV3,
  type EvaluateStayOptiRobustnessCandidateV3,
  type StayOptiAbstentionCodeV3,
  type StayOptiCandidateRegretV3,
  type StayOptiConstraintRelaxationCandidateV3,
  type StayOptiConstraintRelaxationEvaluationV3,
  type StayOptiConstraintRelaxationKindV3,
  type StayOptiDecisionRobustnessOptionsV3,
  type StayOptiDecisionRobustnessV3,
  type StayOptiNearTieV3,
  type StayOptiNoGoodOptionV3,
  type StayOptiRiskSignalCodeV3,
  type StayOptiRiskSignalV3,
  type StayOptiRobustnessCandidateEvaluationV3,
  type StayOptiRobustnessCandidateStatusV3,
  type StayOptiRobustnessScenarioIdV3,
  type StayOptiRobustnessScenarioV3,
  type StayOptiScenarioCandidateScoreV3,
} from "./robustness/decisionRobustnessV3";

export {
  assertContextualStayValueV3,
  evaluateContextualStayValueV3,
  validateContextualStayValueV3,
  type EvaluateStayOptiContextualCandidateInputV3,
  type EvaluateStayOptiContextualStayValueInputV3,
  type StayOptiCancellationInputV3,
  type StayOptiContextInteractionEvaluationV3,
  type StayOptiContextInteractionV3,
  type StayOptiContextualCandidateEvaluationV3,
  type StayOptiContextualCapabilityCodeV3,
  type StayOptiContextualCapabilityInputV3,
  type StayOptiContextualEvidenceSourceV3,
  type StayOptiContextualEvidenceV3,
  type StayOptiContextualSignalIdV3,
  type StayOptiContextualStayContextV3,
  type StayOptiContextualStayValueEvaluationV3,
  type StayOptiContextualStayValueValidationV3,
  type StayOptiConvenienceEvaluationV3,
  type StayOptiDestinationContextV3,
  type StayOptiFlexibilityValueV3,
  type StayOptiFrictionSignalCodeV3,
  type StayOptiFrictionSignalInputV3,
  type StayOptiPaymentInputV3,
  type StayOptiRoomAttributeCodeV3,
  type StayOptiRoomAttributeInputV3,
  type StayOptiRoomOptionInputV3,
  type StayOptiRoomUpgradeEvaluationV3,
  type StayOptiTravelModeV3,
  type StayOptiTravelPointCategoryV3,
  type StayOptiTravelPointInputV3,
  type StayOptiTripSpecificLocationV3,
} from "./contextual/contextualStayValueV3";

export {
  STAYOPTI_EXPLANATION_SLOT_IDS_V3,
  assertDecisionExplanationV3,
  evaluateDecisionExplanationV3,
  validateDecisionExplanationV3,
  type EvaluateStayOptiDecisionExplanationInputV3,
  type StayOptiDecisionExplanationV3,
  type StayOptiDecisionExplanationValidationV3,
  type StayOptiExplanationClaimCodeV3,
  type StayOptiExplanationClaimStatusV3,
  type StayOptiExplanationClaimV3,
  type StayOptiExplanationCopyEvidenceLinkV3,
  type StayOptiExplanationNumericFactCodeV3,
  type StayOptiExplanationNumericFactV3,
  type StayOptiExplanationNumericUnitV3,
  type StayOptiExplanationSlotIdV3,
  type StayOptiExplanationStatusV3,
  type StayOptiExplanationStrengthLabelV3,
} from "./explanation/decisionExplanationV3";

export {
  assertSearchWideScaleCoverageV3,
  evaluateSearchWideScaleCoverageV3,
  validateSearchWideScaleCoverageV3,
  type EvaluateStayOptiSearchWideScaleInputV3,
  type StayOptiRelativeScarcityV3,
  type StayOptiScaleCandidateDispositionV3,
  type StayOptiScaleCandidateEvaluationV3,
  type StayOptiScaleCandidateInputV3,
  type StayOptiScaleEquivalenceAuditV3,
  type StayOptiScaleScopeClaimV3,
  type StayOptiScaleWorkBudgetV3,
  type StayOptiSearchWideContextV3,
  type StayOptiSearchWideScaleCoverageV3,
  type StayOptiSearchWideScaleOptionsV3,
  type StayOptiSearchWideScalePolicyV3,
  type StayOptiSearchWideScaleValidationV3,
  type StayOptiSearchWideScopeV3,
  type StayOptiSourceSetCompletenessV3,
} from "./scale/searchWideScaleCoverageV3";

export {
  STAYOPTI_OUTCOME_EVENT_NAMES_V3,
  assertOutcomeEventV3,
  buildOfflineOutcomeDatasetV3,
  createOutcomeConsentStateV3,
  createOutcomeDataLoopPlanV3,
  createOutcomeEventV3,
  deleteOutcomeSubjectDataV3,
  findOutcomePiiViolationsV3,
  validateOfflineOutcomeDatasetV3,
  validateOutcomeConsentStateV3,
  validateOutcomeDataLoopPlanV3,
  validateOutcomeEventV3,
  type StayOptiBookingAttributedPayloadV3,
  type StayOptiChoiceRecordedPayloadV3,
  type StayOptiDecisionDurationBucketV3,
  type StayOptiDecisionShownPayloadV3,
  type StayOptiDeclaredRegretV3,
  type StayOptiDifferentChoiceReasonV3,
  type StayOptiMainIssueV3,
  type StayOptiOfflineOutcomeDatasetV3,
  type StayOptiOfflineOutcomeRecordV3,
  type StayOptiOutcomeConfidenceBandV3,
  type StayOptiOutcomeConsentInputV3,
  type StayOptiOutcomeConsentStateV3,
  type StayOptiOutcomeCoverageStateV3,
  type StayOptiOutcomeDataLoopPlanV3,
  type StayOptiOutcomeDeletionReceiptV3,
  type StayOptiOutcomeEventInputV3,
  type StayOptiOutcomeEventNameV3,
  type StayOptiOutcomeEventV3,
  type StayOptiOutcomeEventValidationV3,
  type StayOptiOutcomeSolutionKindV3,
  type StayOptiPostStayFeedbackPayloadV3,
  type StayOptiRecheckRecordedPayloadV3,
  type StayOptiRegretCauseV3,
} from "./outcome/outcomeDataLoopV3";

export {
  assertEvaluationCalibrationPlanV3,
  assertEvaluationCalibrationResultV3,
  createBlindEvaluationSetV3,
  createEvaluationCalibrationPlanV3,
  createGoldenDatasetV3,
  evaluateV3AgainstV2Offline,
  validateBlindEvaluationSetV3,
  validateEvaluationCalibrationPlanV3,
  validateEvaluationCalibrationResultV3,
  validateGoldenDatasetV3,
  type StayOptiAbstentionMetricsV3,
  type StayOptiBlindEngineLabelV3,
  type StayOptiBlindEvaluationSetV3,
  type StayOptiBlindEvaluatorTypeV3,
  type StayOptiBlindJudgmentInputV3,
  type StayOptiCalibrationMetricsV3,
  type StayOptiCriticalRegressionCodeV3,
  type StayOptiEngineCaseObservationV3,
  type StayOptiEvaluationCalibrationPlanV3,
  type StayOptiEvaluationCalibrationResultV3,
  type StayOptiEvaluationCoverageV3,
  type StayOptiEvaluationDestinationV3,
  type StayOptiEvaluationDurationV3,
  type StayOptiEvaluationGateStatusV3,
  type StayOptiEvaluationGateV3,
  type StayOptiEvaluationLeadTimeV3,
  type StayOptiEvaluationProfileV3,
  type StayOptiEvaluationSegmentV3,
  type StayOptiEvaluationThresholdsV3,
  type StayOptiEvaluationValidationV3,
  type StayOptiFairnessMetricsV3,
  type StayOptiGoldenCaseInputV3,
  type StayOptiGoldenCaseTypeV3,
  type StayOptiGoldenDatasetV3,
  type StayOptiMetricValueV3,
  type StayOptiMonetaryValueMetricsV3,
  type StayOptiPairwiseGroupV3,
  type StayOptiPairwiseMetricsV3,
  type StayOptiProviderDependenceMetricsV3,
  type StayOptiRegretMetricsV3,
  type StayOptiSegmentDimensionV3,
  type StayOptiSegmentMetricGroupV3,
  type StayOptiSegmentReportV3,
  type StayOptiStabilityMetricsV3,
} from "./evaluation/evaluationCalibrationV3";

export {
  STAYOPTI_REAL_CASE_BLIND_REVIEW_AUDIT_V3,
  createBlindEvaluationFromReviewResponsesV3,
  createRealCaseBlindReviewBundleV3,
  renderBlindReviewHtmlV3,
  validateRealCaseBlindReviewBundleV3,
  type StayOptiBlindAssignmentCaseV3,
  type StayOptiBlindDimensionFactsV3,
  type StayOptiBlindOptionFactsV3,
  type StayOptiBlindReviewAssignmentsV3,
  type StayOptiBlindReviewBundleV3,
  type StayOptiBlindReviewCaseV3,
  type StayOptiBlindReviewPacketV3,
  type StayOptiBlindReviewResponseV3,
  type StayOptiBlindReviewValidationV3,
  type StayOptiBlindTripContextV3,
  type StayOptiRealCaseBlindReviewSourceV3,
  type StayOptiRealCaseSegmentInputV3,
} from "./evaluation/realCaseBlindReviewV3";

export {
  STAYOPTI_ROLE_AWARE_BLIND_ASSIGNMENT_SCHEMA_VERSION_V3,
  STAYOPTI_ROLE_AWARE_BLIND_PACKET_SCHEMA_VERSION_V3,
  STAYOPTI_ROLE_AWARE_BLIND_REVIEW_AUDIT_V3,
  STAYOPTI_ROLE_AWARE_BLIND_REVIEW_VERSION_V3,
  STAYOPTI_ROLE_AWARE_DEBLIND_SCHEMA_VERSION_V3,
  createRoleAwareBlindReviewBundleV3,
  createRoleAwareDeblindReportV3,
  validateRoleAwareBlindReviewBundleV3,
  type StayOptiBlindEngineV3,
  type StayOptiBlindEvaluationRoleV3,
  type StayOptiRoleAwareBlindAssignmentCaseV3,
  type StayOptiRoleAwareBlindAssignmentsV3,
  type StayOptiRoleAwareBlindBundleV3,
  type StayOptiRoleAwareBlindCaseV3,
  type StayOptiRoleAwareBlindPacketV3,
  type StayOptiRoleAwareBlindRejectionV3,
  type StayOptiRoleAwareBlindResponseV3,
  type StayOptiRoleAwareBlindSourceCaseV3,
  type StayOptiRoleAwareBlindValidationV3,
  type StayOptiRoleAwareCandidateV3,
  type StayOptiRoleAwareDeblindJudgmentV3,
  type StayOptiRoleAwareDeblindReportV3,
  type StayOptiRoleAwareDeblindRoleSummaryV3,
  type StayOptiRoleAwareReasonDiffV3,
  type StayOptiRoleAwareRejectionReasonV3,
} from "./evaluation/roleAwareBlindReviewV3";

export {
  STAYOPTI_PROMOTION_THRESHOLDS_V3,
  createDefaultPromotionControlV3,
  createPromotionAuthorizationV3,
  createPromotionReviewV3,
  createServingAssignmentV3,
  createShadowComparisonV3,
  createShadowRegressionDashboardV3,
  evaluatePromotionKillSwitchV3,
  runV3ShadowSafelyV3,
  runV3ShadowWithDerivedSafetySafelyV3,
  validateDefaultPromotionControlV3,
  validateKillSwitchStateV3,
  validatePromotionAuthorizationV3,
  validatePromotionReviewV3,
  validateServingAssignmentV3,
  validateShadowObservationV3,
  validateShadowRegressionDashboardV3,
  type StayOptiCanaryEvidenceV3,
  type StayOptiComparableDecisionRoleV3,
  type StayOptiComparableDecisionStatusV3,
  type StayOptiComparableDecisionV3,
  type StayOptiDefaultPromotionControlV3,
  type StayOptiKillSwitchStateV3,
  type StayOptiPromotionAuditIdentityV3,
  type StayOptiPromotionAuthorizationV3,
  type StayOptiPromotionExternalGatesV3,
  type StayOptiPromotionGateEvidenceV3,
  type StayOptiPromotionGateResultV3,
  type StayOptiPromotionReviewV3,
  type StayOptiPromotionStageV3,
  type StayOptiPromotionThresholdsV3,
  type StayOptiServingAssignmentV3,
  type StayOptiServingEngineV3,
  type StayOptiShadowComparisonV3,
  type StayOptiShadowDecisionDiffV3,
  type StayOptiShadowDiffKindV3,
  type StayOptiShadowErrorV3,
  type StayOptiShadowObservationV3,
  type StayOptiShadowReasonDiffCountV3,
  type StayOptiShadowReasonDiffV3,
  type StayOptiShadowRegressionDashboardV3,
  type StayOptiShadowSafetySignalsV3,
  type StayOptiShadowSegmentMetricV3,
  type StayOptiShadowValidationV3,
} from "./promotion/shadowCanaryPromotionV3";

export {
  STAYOPTI_DECISION_SCIENCE_BIAS_AXES_V3,
  STAYOPTI_DECISION_SCIENCE_DOMAINS_V3,
  STAYOPTI_DECISION_SCIENCE_LIBRARY_AUDIT_V3,
  STAYOPTI_DECISION_SCIENCE_LIBRARY_SCHEMA_VERSION_V3,
  STAYOPTI_DECISION_SCIENCE_LIBRARY_VERSION_V3,
  assertDecisionScienceLibraryV3,
  createDecisionScienceLibraryV3,
  validateDecisionScienceLibraryV3,
  type StayOptiDecisionScienceBiasAxisV3,
  type StayOptiDecisionScienceBiasControlV3,
  type StayOptiDecisionScienceClaimScopeV3,
  type StayOptiDecisionScienceClaimV3,
  type StayOptiDecisionScienceCommercialRiskV3,
  type StayOptiDecisionScienceDomainV3,
  type StayOptiDecisionScienceEvidenceStrengthV3,
  type StayOptiDecisionScienceLibraryInputV3,
  type StayOptiDecisionScienceLibraryV3,
  type StayOptiDecisionScienceSourceTypeV3,
  type StayOptiDecisionScienceSourceV3,
  type StayOptiDecisionScienceTestMapV3,
  type StayOptiDecisionScienceValidationV3,
  type StayOptiDecisionScienceViolationCodeV3,
  type StayOptiDecisionScienceViolationV3,
} from "./research/decisionScienceLibraryV3";
